name: River network issue
description: Report a problem with the river network
title: ""
labels: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Briefly describe the problem.
    validations:
      required: true
